### ISSUE TITLE
Allow dependancies for pip installation

### ISSUE THREAD

**Issue by Tuxem** [geerlingguy/ansible-role-ansible#22]
To install ansible via pip on fresh installs, it might needs somes dependancies (ex : gcc, python-devel, openssl-devel on RHEL)

Example in tasks.yml

```
- name: Install dependancies for pip installation.
  package:
    name: "{{ ansible_pip_dependancies }}"
    state: present
```
